#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\BlogController::index

verNoticia:
 path: /noticia/{id}
 controller: App\Controller\BlogController::verNoticia
 requirements:
  id: '\d+'

nuevaNoticia:
 path: /noticia/nueva
 controller: App\Controller\BlogController::nuevaNoticia

app_noticia_creada:
 path: /noticia/creada
 controller: App\Controller\BlogController::noticiaCreada

app_noticia_lista:
 path: /
 controller: App\Controller\BlogController::listaNoticias

app_noticia_editar:
 path: /noticia/editar/{id}
 controller: App\Controller\BlogController::editarNoticia

app_noticia_borrar:
 path: /noticia/borrar/{id}
 controller: App\Controller\BlogController::borrarNoticia